# Generated by Django 3.2.7 on 2021-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.AddField(
            model_name='report',
            name='file_name',
            field=models.FileField(default='report.pdf', upload_to='report/'),
        ),
    ]
