# Generated by Django 3.2.7 on 2021-11-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20211010_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='file_name',
            new_name='report_file',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='report_name',
        ),
    ]
