# Generated by Django 3.2.7 on 2021-11-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_id_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='id_list',
            new_name='list_id',
        ),
    ]
