# Generated by Django 3.2.7 on 2021-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_rename_id_list_report_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(upload_to='report/'),
        ),
    ]
