# Generated by Django 3.2.7 on 2021-11-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofiles', '0001_initial'),
        ('inventdata', '0007_entrydata_sisa_produk'),
        ('report', '0008_report_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('report_file', models.FileField(upload_to='report3/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminprofiles.adminprofile')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventdata.listdata')),
            ],
        ),
        migrations.CreateModel(
            name='Report2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('report_file', models.FileField(upload_to='report2/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminprofiles.adminprofile')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventdata.listdata')),
            ],
        ),
    ]
