# Generated by Django 3.2.7 on 2021-11-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_report2_report3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
