# Generated by Django 3.2.7 on 2021-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrydata',
            old_name='sisa_produk',
            new_name='sisa_produk_akhir',
        ),
        migrations.AddField(
            model_name='entrydata',
            name='hari_periode',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='entrydata',
            name='sisa_produk_awal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrydata',
            name='tor',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='entrydata',
            name='wsp',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='kuantitas_terjual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
