# Generated by Django 3.2.7 on 2021-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventdata', '0002_auto_20210921_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydata',
            name='hari_periode',
            field=models.PositiveIntegerField(default=365),
        ),
    ]
