# Generated by Django 3.2.7 on 2021-09-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventdata', '0005_alter_entrydata_id_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='inventdata/'),
        ),
    ]
