# Generated by Django 3.2.7 on 2021-11-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventdata', '0006_alter_csv_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydata',
            name='sisa_produk',
            field=models.IntegerField(default=0),
        ),
    ]
